### PR TITLE
refactor: Migrate rewrite from 7 to 8

### PR DESCRIPTION
**Pull request by timtebeek**
Hi all, with the arrival of [Yaml preconditions](https://docs.openrewrite.org/reference/yaml-format-reference#preconditions) I think we've resolved the biggest hurdle in your possible adoption of OpenRewrite 8. I figured to start a [quick automated pull request](https://app.moderne.io/recipes/org.openrewrite.java.upgrade.MigrateToRewrite8) to open the discussion on whether you'd want to move this further.

As you can see there's some comments left to resolve, which refer to [the migration guide](https://docs.openrewrite.org/changelog/8-1-2-release), but as that requires manual work I figured best to coordinate at this point.

I hope to hear what your plans are to move forward, and how we can help facilitate that, such that everyone has the best experience running these recipes.

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks a lot @timtebeek ! We were waiting for this feature before having a look at migrating to 8 but we really appreciate the help!

The core changes look good. I think we will need @JiriOndrusek to have a look at the Camel changes.

@JiriOndrusek I'm thinking of adding you as a maintainer of the repository so that you can push additional changes to this pull request. Does it work for you?

**Comment by JiriOndrusek** [comment]
Hi, I understand, that Camel recipes have to be fixed, in this PR, right? (from the quick look, I see method removed from the openrewrite, which was heavily used in Camel recipes)

Ability to push changes to this PR would help a lot, I agree.

**Comment by gsmet** [comment]
@JiriOndrusek yeah, that's my understanding as well. Don't hesitate to ping Tim in this PR if you have questions.

I sent you an invite to the repository.

**Comment by JiriOndrusek** [comment]
> @JiriOndrusek yeah, that's my understanding as well. Don't hesitate to ping Tim in this PR if you have questions.
> 
> I sent you an invite to the repository.

Thank you! I accepted the invitation a few moments ago. I plan to look at the required changes later today.

**Comment by JiriOndrusek** [comment]
Hi @timtebeek I started fixing the camel recipes as suggested by openrewrite comments.
I'm facing a build problem on my local machine. As the openrewrite dependencies are provided, my maven build fails with errors like:

```
cannot find symbol
[ERROR]   symbol:   class Recipe
[ERROR]   location: package org.openrewrite

```

Do I need to configure the project (or anything other) to make my local build pass?

**Comment by timtebeek** [comment]
I'd not even attempted compilation yet, as I didn't know if this was going to be picked up; I've now pushed https://github.com/quarkusio/quarkus-updates/pull/63/commits/a58914ca3db023d26318bf5a7e8a934936fd28cd which should at least compile; welcome to critique or improve my approach in review.

**Comment by JiriOndrusek** [comment]
No problem, I thought hat I missed something:)
I will be fixing camel recipes tomorrow as I didn't manage to finish it today.
Thanks for the commit!

**Comment by JiriOndrusek** [comment]
@gsmet I tried to push my change to this PR and t was rejected:

```
To github.com:timtebeek/quarkus-updates.git
 ! [remote rejected] refactor/rewrite-from-7-to-8 -> refactor/rewrite-from-7-to-8 (permission denied)
error: failed to push some refs to 'github.com:timtebeek/quarkus-updates.git'
```

I was using command `git push timtebeek refactor/rewrite-from-7-to-8 `
where the remote is:

```
timtebeek	git@github.com:timtebeek/quarkus-updates.git (fetch)
timtebeek	git@github.com:timtebeek/quarkus-updates.git (push)
```

**Comment by JiriOndrusek** [comment]
@timtebeek I fixed the Camel recipes (and tests) and I keep the fix in my fork, until I figure how to add it to this PR. My commit is https://github.com/JiriOndrusek/quarkus-updates/commit/e144808ed39f8f56176165510864ae2143c0fc7a

(The change is the simplest possible to make the recipe tests work. I'd like to spend more time and discover whether some code could be refactored with the new version of Openrewrite)

**Comment by gsmet** [comment]
It's weird. I can confirm that you have the proper permissions.

**Comment by gsmet** [comment]
You can create another PR, but please keep the commits of @timtebeek as they are so that we don't lose authorship.

**Comment by JiriOndrusek** [comment]
> It's weird. I can confirm that you have the proper permissions.

I checked the `tmtebbek's` branch by `git checkout -b refactor/rewrite-from-7-to-8 timtebeek/refactor/migrate-rewrite-from-7-to-8`
I added 1 commit to the branch and then pushed by `git push timtebeek refactor/rewrite-from-7-to-8 `.

TBH I  never tried that before, but according to the guide I found, this should be the right approach.

**Comment by JiriOndrusek** [comment]
Superseded by https://github.com/quarkusio/quarkus-updates/pull/64

(Original commits are untouched in the new PR)

**Comment by timtebeek** [comment]
All good; I tend to use the GitHub CLI to checkout and work on forks: `gh co 63`, and after that `git push` works from the command line. But ok to continue in #64; thanks for taking this on! I'll close this PR.

**Pull request closed without merging**
