### PR TITLE
Fixing typos, removing duplicated code and adding preconditions to recipes

### PR DESCRIPTION
**Pull request by ammachado**

### CODE REVIEW

**Comment by gsmet** [comment]
@JiriOndrusek I let you have a look at these changes, I know you were working on extracting these recipes so not sure if it's ideal to apply this now.
But you could probably apply the diff to your new code?

**Comment by JiriOndrusek** [comment]
@gsmet thanks for the information. I think that it is still the right time to apply this changes. Extraction of the recipes has a lower priority for me now, because I need to get confirmation, that it would be beneficial for the other project to use them. Therefore I'll check this changes later today.

**Comment by ammachado** [comment]
@gsmet @JiriOndrusek I was considering extracting these recipes to a separate project myself. I am willing to contribute some generic Camel recipes I have created.

**Comment by JiriOndrusek** [comment]
PR looks good from my POV. 
Thanks @ammachado for the fixes/changes!
We can discuss separation of the recipes. I started with copying the recipes without considering possible impacts - just to see whether it is possible to separate junit tests too.

**Comment by gsmet** [comment]
Thanks @ammachado !

**Pull request merged**
