### PR TITLE
Move upgrade recipe to META-INF/rewrite

### PR DESCRIPTION
**Pull request by rsynek**
This repository is already deployed to Maven Central. If the recipe `.yaml` file is located in META-INF/rewrite, the rewrite maven plugin can see it in the dependencies:
https://docs.openrewrite.org/concepts-and-explanations/environment

Then, it makes it possible to use the recipe in other projects as follows:
` mvn clean org.openrewrite.maven:rewrite-maven-plugin:LATEST:run -Drewrite.recipeArtifactCoordinates=io.quarkus:quarkus-update-recipes:0.0.3 -Drewrite.activeRecipes=org.example.MyRecipe -Drewrite.configLocation=my-recipe.yml`

The `my-recipe.yml` is a top-level recipe that calls the individual `javax-jakarta` migration rules similarly to https://github.com/quarkusio/jbang-catalog/blob/main/quarkus3.yml.

The same approach could be taken in the JBang migration script instead of merging the two yaml files.

@aloubyansky @gsmet what do you think?

Please note that after merging this PR, the URL here: https://github.com/quarkusio/jbang-catalog/blob/main/q3upgrade.java#L48 needs to be updated.

### CODE REVIEW

**Comment by aloubyansky** [comment]
There was an idea to include other Quarkiverse extension-specific migration recipes in this repo for which a directory layout convention would be used to locate the relevant recipes.

fyi @ia3andy

**Comment by rsynek** [comment]
@aloubyansky that could be an option; so far, speaking about OptaPlanner, Drools, and Kogito, these projects automatically migrate to Jakarta to provide compatibility with both parts of the ecosystem (similarly to what Hibernate 5 did).

But apart from migrating these projects themselves, there also has to be a migration path for their users, which sometimes may need some changes, resulting in a second top-level recipe.

CC @radtriste

**Comment by rsynek** [comment]
@ia3andy any thoughts about my proposal?

**Comment by ia3andy** [comment]
It is a good idea, the problem is that those recipes are not really relevant by themselves, they are meant to be consumed by the update tool that we are working on in Quarkus core.

Do you have a use case where they would be needed outside the Quarkus update tool?

**Comment by rsynek** [comment]
@ia3andy is the update tool meant to update Quarkus itself or any Java EE (quarkus-based) application?

Here are my cases:
- As a developer on a project (OptaPlanner) that is a part of the Quarkus platform, I want to automatically migrate to Quarkus 3 to still participate in the platform. At the same time, the project needs to stay compatible also with Quarkus 2 (that's why we do automated migration, similarly to what Hibernate 5 did with the `-jakarta` suffix).
- As an OptaPlanner user, I want my project to migrate to the Jakarta version of OptaPlanner, which supports Quarkus 3.

Both these cases are 99% Quarkus migration and the rest are the OptaPlanner-specific migration steps. I would be surprised if other projects in the platform didn't consider at least the second use case - migrating their users.

For that reason, I am looking into options for how to efficiently reuse the Quarkus migration recipe. Right now, we have a slightly modified copy of it in the OptaPlanner repo. Please note that running the Quarkus recipe alone without the project-specific steps leaves the project broken. That's why I need to apply both in a single OpenRewrite run.

**Comment by ia3andy** [comment]
@rsynek could you try to put it in `META-INF/rewrite/core` and see if it still works?
Also I wonder the behavior if there are conflict between recipes files?

**Comment by rsynek** [comment]
> META-INF/rewrite/core

@ia3andy Sorry for the late reply; no, it works only in the `META-INF/rewrite` directory. If I put it `META-INF/rewrite/core`, OpenRewrite cannot find the individual recipes.

**Comment by ia3andy** [comment]
> > META-INF/rewrite/core
> 
> @ia3andy Sorry for the late reply; no, it works only in the `META-INF/rewrite` directory. If I put it `META-INF/rewrite/core`, OpenRewrite cannot find the individual recipes.

Ok then what I suggest is that we integrate this to the build so that it copy all the recipes as a flat list in the `META-INF/rewrite/`

The reason is that we will have multiple directories `core` is quarkus core, but extensions will also provide recipes: `io.quarkiverse.quinoa/quarkus-quinoa/...`

**Comment by ia3andy** [comment]
@rsynek would you provide a new PR?

**Pull request closed without merging**
