### PR TITLE
Migrate @NativeTest to @QuarkusIntegrationTest

### PR DESCRIPTION
**Pull request by gastaldi**
- Related to https://github.com/quarkusio/quarkus/pull/31048

### CODE REVIEW

**Comment by gastaldi** [comment]
Regardless if the annotation is removed or not, it's always a good idea to not use deprecated annotations :)

**Comment by maxandersen** [comment]
I thought there was more to it than just change the annotation ?

**Comment by gastaldi** [comment]
@maxandersen nope, just changing these two annotations are enough

**Review by gsmet — CHANGES_REQUESTED** [review]
Please let's not merge this right now as I made massive changes to this file that are coming soon.

We can integrate this afterwards.

**Comment by gsmet** [comment]
I integrated this work in mine. Thanks!

**Pull request closed without merging**
