### PR TITLE
Refactor/rewrite from 7 to 8

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Replaces https://github.com/quarkusio/quarkus-updates/pull/63

### CODE REVIEW

**Comment by gsmet** [comment]
@JiriOndrusek @timtebeek thanks for this. I will have a look at a few projects to make sure I can't spot a regression.

**Comment by gsmet** [comment]
@JiriOndrusek apart from getting the tests green, I recommend that you also test on sample projects as when we release the new version of quarkus-updates, even older Quarkus versions will use it.

**Comment by JiriOndrusek** [comment]
> @JiriOndrusek apart from getting the tests green, I recommend that you also test on sample projects as when we release the new version of quarkus-updates, even older Quarkus versions will use it.

Yes I agree and will do that.  So far, I executed update over a simple project and see some errors. 

1. Is it possible that CLI/plugin tool uses 7.x openrewrite libraries? If so, it could be the reason of the problems
2. Or there is some not-back-compatible changes in openrewrite and some yaml recipes which worked in 7.x are wrong for 8.x.

Here is the log (with -X), which does not say where the error is happening.
```
[INFO] Validating active recipes...
[ERROR] Recipe validation error in oldArtifactId: is required
[ERROR] Recipe validation error in oldGroupId: is required
[ERROR] Recipe validation error in oldArtifactId: is required
[ERROR] Recipe validation error in oldGroupId: is required
[ERROR] Recipe validation error in oldArtifactId: is required
[ERROR] Recipe validation error in oldGroupId: is required
[ERROR] Recipe validation error in oldArtifactId: is required
[ERROR] Recipe validation error in oldGroupId: is required
[ERROR] Recipe validation errors detected as part of one or more activeRecipe(s). Execution will continue regardless.
```

(The update finished successfully, but I think that those recipes with errors, might not be applied.
I'll find on Monday, which openrewrite recipes contain errors and if possible, I'll fix it.

**Comment by gsmet** [comment]
@JiriOndrusek I don't think so, we are supposed to apply the Maven plugin as is. I'll have a look on Monday, I'm busy on others things today.

**Comment by timtebeek** [comment]
Might be worth picking up this suggestion as well, to also support Gradle projects in much the same way.
- https://github.com/quarkusio/quarkus-updates/issues/65

**Comment by JiriOndrusek** [comment]
Hi @timtebeek thanks for suggesting that. I was (and still a little bit am) ill for the past few days. I'll look at that as soon as I start working.

**Comment by gsmet** [comment]
@JiriOndrusek I will experiment with this today and I will give @timtebeek 's suggestion a try in passing.

Get some rest and get well soon :).

**Comment by gsmet** [comment]
I fixed the issue `[ERROR] Recipe validation error in oldArtifactId: is required`, a recipe was incorrect.

I switched to the Java recipes abstraction where it made sense.

I added some very basic tests for the core updates, I will add a lot more in the coming days/weeks.

I also did a pass on modernizing/cleaning up the build.

Thanks everyone for the collaboration and especially @timtebeek for initiating this effort!

**Pull request merged**
